### ISSUE TITLE
AprilTag detection rate is low on DSLR high resolution images

### ISSUE THREAD

**Issue by tomriddle1234** [simbaforrest/cv2cg#5]
I tested your AprilTag creation and detection code in cv2cg with my Nikon D7100 6000x4000 images, but got worse detection rate than normal web cam, I would like to ask any idea about tweaking the parameters or other suggestions please.

**Comment by simbaforrest** [comment]
Hi Jianming, sorry I am writing my dissertation and didn't notice your issue. 6000x4000 could lead to low speed but detection rate should remain the same. If you could send me some sample images I might have a chance to check later.
